GetAppMetadata.exe  	books_and_reference	  	10
GetAppMetadata.exe  	business	  	10
GetAppMetadata.exe  	comics	  	10
GetAppMetadata.exe  	communication	  	10
GetAppMetadata.exe  	education	  	10
GetAppMetadata.exe  	entertainment	  	10
GetAppMetadata.exe  	finance	  	10
GetAppMetadata.exe  	health_and_fitness	  	10
GetAppMetadata.exe  	libraries_and_demo	  	10
GetAppMetadata.exe  	lifestyle	  	10
GetAppMetadata.exe  	media_and_video	  	10
GetAppMetadata.exe  	medical	  	10
GetAppMetadata.exe  	music_and_audio	  	10
GetAppMetadata.exe  	news_and_magazines	  	10
GetAppMetadata.exe  	personalization	  	10
GetAppMetadata.exe  	photography	  	10
GetAppMetadata.exe  	productivity	  	10
GetAppMetadata.exe  	shopping	  	10
GetAppMetadata.exe  	social	  	10
GetAppMetadata.exe  	sports	  	10
GetAppMetadata.exe  	tools	  	10
GetAppMetadata.exe  	transportation	  	10
GetAppMetadata.exe  	travel_and_local	  	10
GetAppMetadata.exe  	weather	  	10
